global:
  scrape_interval: 10s          # How often to scrape metrics by default
  evaluation_interval: 10s      # How often rules are evaluated

scrape_configs:
  - job_name: 'prometheus'      # Prometheus monitors itself
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'            # Node Exporter metrics
    static_configs:
      - targets: ['node-exporter:9100']
